@startuml
package lab-client {
    class Asker {
      + askBand(Console, Long): MusicBand
      - askStudio(Console): Studio
      - askCoordinates(Console): Coordinates
    }
    class Client {
      - networkManager: NetworkManager
      - attempts: int
      - SERVER_PORT: int
      - scriptStackCounter: int
      - console: Console
      - commandsData: Map<String, Pair<ArgumentValidator, Boolean>>
      - SERVER_HOST: String
      - askingRequest(Console, String): Request
      - validateCommand(String[]): ExecutionStatus
      + main(String[]): void
      - prepareRequest(Console, String): Request
      - runScript(String): ExecutionStatus
    }
    interface Console << interface >> {
      + println(Object): void
      + printError(Object): void
      + readln(): String
      + print(Object): void
    }
    class ElementValidator {
      + validating(MusicBand): Pair<ExecutionStatus, MusicBand>
      + validateAsking(Console, Long): Pair<ExecutionStatus, MusicBand>
    }
    class FileConsole {
      - input: BufferedReader
      + print(Object): void
      + readln(): String
      + printError(Object): void
      + println(Object): void
    }
    class NetworkManager {
      - channel: SocketChannel
      - PORT: int
      - SERVER_HOST: String
      + connect(): void
      + close(): void
      + receive(): Response
      + send(Request): void
    }
    class StandartConsole {
      + println(Object): void
      + print(Object): void
      + printError(Object): void
      + readln(): String
    }
}

package lab-common {
    class ArgumentValidator {
      + validate(String, String): ExecutionStatus
    }
    class Coordinates {
      - serialVersionUID: long
      - y: Integer
      - x: double
      + equals(Object): boolean
      + getX(): double
      + toString(): String
      + hashCode(): int
      + validate(): boolean
      + getY(): Integer
    }
    class Element {
      + getID(): Long
    }
    class EmptyValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class ExecutionStatus {
      - serialVersionUID: long
      - message: String
      - status: boolean
      - collection: Stack<MusicBand>
      + isSuccess(): boolean
      + getCollection(): Stack<MusicBand>
      + getMessage(): String
    }
    class GenreValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class IdValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class MusicBand {
      - description: String
      - serialVersionUID: long
      - name: String
      - creationDate: LocalDateTime
      - albumsCount: Long
      - studio: Studio
      - numberOfParticipants: Long
      - id: Long
      - coordinates: Coordinates
      - genre: MusicGenre
      + toArray(MusicBand): String[]
      + hashCode(): int
      + getId(): Long
      + toString(): String
      + getGenre(): MusicGenre
      + validate(): boolean
      + fromArray(String[]): MusicBand
      + getName(): String
      + compareTo(Element): int
      + getAlbumsCount(): Long
      + equals(Object): boolean
      + getCreationDate(): LocalDateTime
      + getNumberOfParticipants(): Long
      + updateId(Long): void
      + getDescription(): String
      + getStudio(): Studio
      + getCoordinates(): Coordinates
      + getID(): Long
    }
    enum MusicGenre << enumeration >> {
      + JAZZ:
      + MATH_ROCK:
      + BRIT_POP:
      + values(): MusicGenre[]
      + valueOf(String): MusicGenre
      + list(): String
    }
    class Pair<A, B> {
      - b: B
      - serialVersionUID: long
      - a: A
      + setSecond(B): void
      + getFirst(): A
      + setFirst(A): void
      + getSecond(): B
    }
    class Request {
      - string: String
      - serialVersionUID: long
      - band: MusicBand
      + getCommand(): String[]
      + getBand(): MusicBand
      + toString(): String
    }
    class Response {
      - serialVersionUID: long
      - executionStatus: ExecutionStatus
      - commandsData: Map<String, Pair<ArgumentValidator, Boolean>>
      + toString(): String
      + getCommandsMap(): Map<String, Pair<ArgumentValidator, Boolean>>
      + getExecutionStatus(): ExecutionStatus
    }
    class Studio {
      - name: String
      - serialVersionUID: long
      - address: String
      + validate(): boolean
      + toString(): String
      + equals(Object): boolean
      + getName(): String
      + getAddress(): String
      + hashCode(): int
    }
    interface Validatable << interface >> {
      + validate(): boolean
    }
}

package lab-server {
    class Add {
      # runInternal(MusicBand): ExecutionStatus
    }
    class AddIfMin {
      # runInternal(MusicBand): ExecutionStatus
    }
    class AskingCommand<T> {
      # runInternal(String): ExecutionStatus
      + run(String): ExecutionStatus
      + run(String, MusicBand): ExecutionStatus
      # runInternal(MusicBand): ExecutionStatus
    }
    class Clear {
      # runInternal(String): ExecutionStatus
    }
    class CollectionManager {
      - bands: Map<Long, MusicBand>
      - dumpManager: DumpManager
      - lastSaveDate: LocalDateTime
      - collection: Stack<MusicBand>
      - instance: CollectionManager
      - initializationDate: LocalDateTime
      - id: Long
      + getFreeId(): Long
      + getBands(): Stack<MusicBand>
      + getInitializationDate(): LocalDateTime
      + getById(Long): MusicBand
      + sort(): void
      + add(MusicBand): boolean
      + loadCollection(): ExecutionStatus
      + clear(): void
      + getCollection(): Stack<MusicBand>
      + saveCollection(): void
      + removeAllByGenre(MusicGenre): int
      + removeFirst(): void
      + getLastSaveDate(): LocalDateTime
      + getInstance(): CollectionManager
      + removeById(Long): void
    }
    class Command<T> {
      + argumentValidator: T
      # collectionManager: CollectionManager
      - nameAndDescription: Pair<String, String>
      + run(String): ExecutionStatus
      + hashCode(): int
      + getArgumentValidator(): T
      # runInternal(String): ExecutionStatus
      + equals(Object): boolean
      + getDescription(): String
      + toString(): String
      + getName(): String
    }
    class CommandManager {
      - commands: Map<String, Command<?>>
      + getCommand(String): Command<?>
      + getCommandsMap(): Map<String, Command<?>>
      + register(String, Command<?>): void
    }
    enum CommandNames << enumeration >> {
      + REMOVE_FIRST:
      + EXECUTE_SCRIPT:
      + UPDATE:
      + ADD:
      + REMOVE_BY_ID:
      + ADD_IF_MIN:
      + EXIT:
      + PRINT_FIELD_DESCENDING_DESCRIPTION:
      + HELP:
      + CLEAR:
      + REMOVE_ALL_BY_GENRE:
      + PRINT_FIELD_ASCENDING_DESCRIPTION:
      + SHOW:
      + SORT:
      + INFO:
      - commandDescription: Pair<String, String>
      + valueOf(String): CommandNames
      + values(): CommandNames[]
      + getName(): String
      + getDescription(): String
    }
    class DumpManager {
      - instance: DumpManager
      - filePath: String
      + getInstance(): DumpManager
      + WriteCollection(Stack<MusicBand>): ExecutionStatus
      + ReadCollection(Stack<MusicBand>): ExecutionStatus
    }
    class ExecuteScript {
      + runInternal(String): ExecutionStatus
    }
    class Executer {
      - commandManager: CommandManager
      - validateCommand(String[]): ExecutionStatus
      + runCommand(String[], MusicBand): ExecutionStatus
    }
    class Exit {
      # runInternal(String): ExecutionStatus
    }
    class Help {
      - commandManager: CommandManager
      # runInternal(String): ExecutionStatus
    }
    class Info {
      # runInternal(String): ExecutionStatus
    }
    class PrintFieldAscendingDescription {
      # runInternal(String): ExecutionStatus
    }
    class PrintFieldDescendingDescription {
      # runInternal(String): ExecutionStatus
    }
    class RemoveAllByGenre {
      + runInternal(String): ExecutionStatus
    }
    class RemoveById {
      # runInternal(String): ExecutionStatus
    }
    class RemoveFirst {
      # runInternal(String): ExecutionStatus
    }
    class Server {
      - response: Response
      - selector: Selector
      - collectionManager: CollectionManager
      + logger: Logger
      - isRunning: boolean
      - commandManager: CommandManager
      - PORT: int
      - networkManager: ServerNetworkManager
      + run(Executer): void
      - getConsoleHandler(): ConsoleHandler
      - initLogger(): void
      + main(String[]): void
      - InitialCommandsData(SocketChannel, SelectionKey): void
    }
    class ServerNetworkManager {
      - serverChannel: ServerSocketChannel
      - PORT: int
      + receive(SocketChannel, SelectionKey): Request
      + close(): void
      + startServer(): void
      + getServerSocketChannel(): ServerSocketChannel
      + send(Response, SocketChannel): void
    }
    class Show {
      # runInternal(String): ExecutionStatus
    }
    class Sort {
      # runInternal(String): ExecutionStatus
    }
    class Update {
      # runInternal(MusicBand): ExecutionStatus
    }
}

Add                              -[#000082,plain]-^  AskingCommand                   
AddIfMin                         -[#000082,plain]-^  AskingCommand                   
AskingCommand                    -[#595959,dashed]->  ArgumentValidator
AskingCommand                    -[#000082,plain]-^  Command
Clear                            -[#000082,plain]-^  Command
Command                          -[#595959,dashed]->  ArgumentValidator
Coordinates                      -[#008200,dashed]-^  Validatable
Element                          -[#008200,dashed]-^  Validatable
EmptyValidator                   -[#000082,plain]-^  ArgumentValidator
ExecuteScript                    -[#000082,plain]-^  Command
Exit                             -[#000082,plain]-^  Command
FileConsole                      -[#008200,dashed]-^  Console
GenreValidator                   -[#000082,plain]-^  ArgumentValidator
Help                             -[#000082,plain]-^  Command
IdValidator                      -[#000082,plain]-^  ArgumentValidator
Info                             -[#000082,plain]-^  Command
MusicBand                        -[#000082,plain]-^  Element
PrintFieldAscendingDescription   -[#000082,plain]-^  Command
PrintFieldDescendingDescription  -[#000082,plain]-^  Command
RemoveAllByGenre                 -[#000082,plain]-^  Command
RemoveById                       -[#000082,plain]-^  Command
RemoveFirst                      -[#000082,plain]-^  Command
Show                             -[#000082,plain]-^  Command
Sort                             -[#000082,plain]-^  Command
StandartConsole                  -[#008200,dashed]-^  Console
Studio                           -[#008200,dashed]-^  Validatable
Update                           -[#000082,plain]-^  AskingCommand
@enduml
