@startuml
package lab-client {
    class Asker {
      - askStudio(Console): Studio
      + askBand(Console): MusicBand
      - askCoordinates(Console): Coordinates
    }
    class AuthenticationManager {
      + authenticateUser(NetworkManager, Console): Pair<String, String>
      - getHash(String): String
    }
    class Client {
      - console: Console
      - SERVER_HOST: String
      - networkManager: NetworkManager
      + user: Pair<String, String>
      - commandsData: Map<String, Pair<ArgumentValidator, Boolean>>
      - SERVER_PORT: int
      - attempts: int
      - scriptStackCounter: int
      - validateCommand(String[]): ExecutionStatus
      - prepareRequest(Console, String): Request
      - runScript(String): ExecutionStatus
      - askingRequest(Console, String): Request
      + main(String[]): void
    }
    interface Console << interface >> {
      + printError(Object): void
      + println(Object): void
      + readln(): String
      + print(Object): void
    }
    class ElementValidator {
      + validating(MusicBand): Pair<ExecutionStatus, MusicBand>
      + validateAsking(Console): Pair<ExecutionStatus, MusicBand>
    }
    class FileConsole {
      - input: BufferedReader
      + println(Object): void
      + readln(): String
      + print(Object): void
      + printError(Object): void
    }
    class NetworkManager {
      - PORT: int
      - channel: SocketChannel
      - SERVER_HOST: String
      + send(Request): void
      + connect(): void
      + close(): void
      + receive(): Response
    }
    class StandartConsole {
      + println(Object): void
      + readln(): String
      + print(Object): void
      + printError(Object): void
    }
}

package lab-common {
    class ArgumentValidator {
      + validate(String, String): ExecutionStatus
    }
    class Coordinates {
      - x: double
      - serialVersionUID: long
      - y: Integer
      + validate(): boolean
      + getX(): double
      + hashCode(): int
      + toString(): String
      + getY(): Integer
      + equals(Object): boolean
    }
    class Element {
      + getID(): Long
    }
    class EmptyValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class ExecutionStatus {
      - message: String
      - collection: Stack<MusicBand>
      - serialVersionUID: long
      - status: boolean
      + isSuccess(): boolean
      + getMessage(): String
      + getCollection(): Stack<MusicBand>
    }
    class GenreValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class IdValidator {
      - serialVersionUID: long
      + validate(String, String): ExecutionStatus
    }
    class MusicBand {
      - user: String
      - id: Long
      - coordinates: Coordinates
      - numberOfParticipants: Long
      - description: String
      - creationDate: LocalDateTime
      - studio: Studio
      - genre: MusicGenre
      - serialVersionUID: long
      - name: String
      - albumsCount: Long
      + getStudio(): Studio
      + setGenre(MusicGenre): void
      + getCreationDate(): LocalDateTime
      + validate(): boolean
      + setStudio(Studio): void
      + equals(Object): boolean
      + hashCode(): int
      + toString(): String
      + getNumberOfParticipants(): Long
      + getDescription(): String
      + getId(): Long
      + setNumberOfParticipants(Long): void
      + getCoordinates(): Coordinates
      + getGenre(): MusicGenre
      + setCoordinates(Coordinates): void
      + compareTo(Element): int
      + getName(): String
      + setId(Long): void
      + setAlbumsCount(Long): void
      + setDescription(String): void
      + getID(): Long
      + getAlbumsCount(): Long
      + setName(String): void
      + getUser(): String
    }
    enum MusicGenre << enumeration >> {
      + MATH_ROCK:
      + BRIT_POP:
      + JAZZ:
      + list(): String
      + values(): MusicGenre[]
      + valueOf(String): MusicGenre
    }
    class Pair<A, B> {
      - b: B
      - serialVersionUID: long
      - a: A
      + getFirst(): A
      + getSecond(): B
      + setFirst(A): void
      + setSecond(B): void
    }
    class Request {
      - band: MusicBand
      - user: Pair<String, String>
      - string: String
      - serialVersionUID: long
      + getBand(): MusicBand
      + getUser(): Pair<String, String>
      + toString(): String
      + getCommand(): String[]
    }
    class Response {
      - commandsData: Map<String, Pair<ArgumentValidator, Boolean>>
      - User: Pair<String, String>
      - executionStatus: ExecutionStatus
      - serialVersionUID: long
      + getExecutionStatus(): ExecutionStatus
      + getCommandsMap(): Map<String, Pair<ArgumentValidator, Boolean>>
      + toString(): String
    }
    class Studio {
      - name: String
      - serialVersionUID: long
      - address: String
      + hashCode(): int
      + getName(): String
      + getAddress(): String
      + toString(): String
      + validate(): boolean
      + equals(Object): boolean
    }
    interface Validatable << interface >> {
      + validate(): boolean
    }
}

package lab-server {
    class Add {
      # runInternal(MusicBand, Pair<String, String>): ExecutionStatus
    }
    class AddIfMin {
      # runInternal(MusicBand, Pair<String, String>): ExecutionStatus
    }
    class AskingCommand<T> {
      + run(String, Pair<String, String>): ExecutionStatus
      # runInternal(MusicBand, Pair<String, String>): ExecutionStatus
      # runInternal(String, Pair<String, String>): ExecutionStatus
      + run(String, MusicBand, Pair<String, String>): ExecutionStatus
    }
    class Clear {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    interface CollectionManager << interface >> {
      + getBands(): Stack<MusicBand>
      + getInitializationDate(): LocalDateTime
      + add(MusicBand, Pair<String, String>): ExecutionStatus
      + getById(Long): MusicBand
      + removeById(Long, Pair<String, String>): ExecutionStatus
      + removeFirst(Pair<String, String>): ExecutionStatus
      + removeAllByGenre(MusicGenre, Pair<String, String>): ExecutionStatus
      + getCollection(): Stack<MusicBand>
      + getLastSaveDate(): LocalDateTime
      + sort(): void
      + loadCollection(): ExecutionStatus
      + update(MusicBand, Pair<String, String>): ExecutionStatus
      + clear(Pair<String, String>): ExecutionStatus
    }
    class CollectionManagerMain {
      - initializationDate: LocalDateTime
      - lastSaveDate: LocalDateTime
      - dbManager: DBManager
      - instance: CollectionManagerMain
      - lock: ReadWriteLock
      - bandsMap: Map<Long, MusicBand>
      - collection: Stack<MusicBand>
      + update(MusicBand, Pair<String, String>): ExecutionStatus
      + clear(Pair<String, String>): ExecutionStatus
      + getCollection(): Stack<MusicBand>
      + loadCollection(): ExecutionStatus
      + getBands(): Stack<MusicBand>
      + add(MusicBand, Pair<String, String>): ExecutionStatus
      + getInstance(): CollectionManagerMain
      + removeAllByGenre(MusicGenre, Pair<String, String>): ExecutionStatus
      + getLastSaveDate(): LocalDateTime
      + removeById(Long, Pair<String, String>): ExecutionStatus
      + sort(): void
      + getInitializationDate(): LocalDateTime
      + removeFirst(Pair<String, String>): ExecutionStatus
      + getById(Long): MusicBand
    }
    class CollectionManagerProxy {
      - bandsMap: Map<Long, MusicBand>
      - collection: Stack<MusicBand>
      - instance: CollectionManagerProxy
      - collectionManagerMain: CollectionManagerMain
      - isCacheValid: boolean
      + removeFirst(Pair<String, String>): ExecutionStatus
      + update(MusicBand, Pair<String, String>): ExecutionStatus
      + getInitializationDate(): LocalDateTime
      + add(MusicBand, Pair<String, String>): ExecutionStatus
      + clear(Pair<String, String>): ExecutionStatus
      + getById(Long): MusicBand
      + loadCollection(): ExecutionStatus
      + sort(): void
      + removeById(Long, Pair<String, String>): ExecutionStatus
      + getLastSaveDate(): LocalDateTime
      - refreshCache(): void
      + getBands(): Stack<MusicBand>
      + removeAllByGenre(MusicGenre, Pair<String, String>): ExecutionStatus
      + getCollection(): Stack<MusicBand>
      + getInstance(): CollectionManagerProxy
    }
    class Command<T> {
      + argumentValidator: T
      # collectionManager: CollectionManager
      - nameAndDescription: Pair<String, String>
      + getArgumentValidator(): T
      + hashCode(): int
      # runInternal(String, Pair<String, String>): ExecutionStatus
      + toString(): String
      + getDescription(): String
      + equals(Object): boolean
      + run(String, Pair<String, String>): ExecutionStatus
      + getName(): String
    }
    class CommandManager {
      - commands: Map<String, Command<?>>
      + getCommandsMap(): Map<String, Command<?>>
      + register(String, Command<?>): void
      + getCommand(String): Command<?>
    }
    enum CommandNames << enumeration >> {
      + ADD_IF_MIN:
      + PRINT_FIELD_DESCENDING_DESCRIPTION:
      + EXECUTE_SCRIPT:
      + REMOVE_FIRST:
      + SHOW:
      - commandDescription: Pair<String, String>
      + CLEAR:
      + EXIT:
      + UPDATE:
      + SORT:
      + REMOVE_BY_ID:
      + HELP:
      + INFO:
      + REMOVE_ALL_BY_GENRE:
      + ADD:
      + PRINT_FIELD_ASCENDING_DESCRIPTION:
      + values(): CommandNames[]
      + valueOf(String): CommandNames
      + getName(): String
      + getDescription(): String
    }
    class DBManager {
      - connection: Connection
      - instance: DBManager
      + getInstance(): DBManager
      + removeAllByGenre(MusicGenre, Pair<String, String>): ExecutionStatus
      + checkPassword(Pair<String, String>): ExecutionStatus
      + clear(Pair<String, String>): ExecutionStatus
      + loadCollection(Stack<MusicBand>): ExecutionStatus
      + updateMusicBand(MusicBand, Pair<String, String>): ExecutionStatus
      - checkUser(Pair<String, String>): ExecutionStatus
      + addMusicBand(MusicBand, Pair<String, String>): ExecutionStatus
      + addUser(Pair<String, String>): ExecutionStatus
      + removeById(Long, Pair<String, String>): ExecutionStatus
    }
    class ExecuteScript {
      + runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Executer {
      - commandManager: CommandManager
      + runCommand(String[], MusicBand, Pair<String, String>): ExecutionStatus
      - validateCommand(String[]): ExecutionStatus
    }
    class Exit {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Help {
      - commandManager: CommandManager
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Info {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class PrintFieldAscendingDescription {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class PrintFieldDescendingDescription {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class RemoveAllByGenre {
      + runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class RemoveById {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class RemoveFirst {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Server {
      - selector: Selector
      + logger: Logger
      - networkManager: ServerNetworkManager
      - executer: Executer
      - collectionManager: CollectionManager
      - responses: Map<SocketChannel, Response>
      - commandManager: CommandManager
      - PORT: int
      - initLogger(): void
      + main(String[]): void
      - getFormatter(): Formatter
      - processRequest(SocketChannel, Request): void
      - initialCommandsData(SocketChannel, SelectionKey): void
      + run(): void
      - getProcessRequestThread(SocketChannel, Request, SelectionKey): Thread
    }
    class ServerNetworkManager {
      - serverChannel: ServerSocketChannel
      - PORT: int
      + close(): void
      + send(Response, SocketChannel): void
      + receive(SocketChannel, SelectionKey): Request
      + getServerSocketChannel(): ServerSocketChannel
      + startServer(): void
    }
    class Show {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Sort {
      # runInternal(String, Pair<String, String>): ExecutionStatus
    }
    class Update {
      # runInternal(MusicBand, Pair<String, String>): ExecutionStatus
    }
}

Add                              -[#000082,plain]-^  AskingCommand                   
AddIfMin                         -[#000082,plain]-^  AskingCommand                   
AskingCommand                    -[#595959,dashed]->  ArgumentValidator
AskingCommand                    -[#000082,plain]-^  Command
Clear                            -[#000082,plain]-^  Command
CollectionManagerMain            -[#008200,dashed]-^  CollectionManager
CollectionManagerProxy           -[#008200,dashed]-^  CollectionManager
Command                          -[#595959,dashed]->  ArgumentValidator
Coordinates                      -[#008200,dashed]-^  Validatable
Element                          -[#008200,dashed]-^  Validatable
EmptyValidator                   -[#000082,plain]-^  ArgumentValidator
ExecuteScript                    -[#000082,plain]-^  Command
Exit                             -[#000082,plain]-^  Command
FileConsole                      -[#008200,dashed]-^  Console
GenreValidator                   -[#000082,plain]-^  ArgumentValidator
Help                             -[#000082,plain]-^  Command
IdValidator                      -[#000082,plain]-^  ArgumentValidator
Info                             -[#000082,plain]-^  Command
MusicBand                        -[#000082,plain]-^  Element
PrintFieldAscendingDescription   -[#000082,plain]-^  Command
PrintFieldDescendingDescription  -[#000082,plain]-^  Command
RemoveAllByGenre                 -[#000082,plain]-^  Command
RemoveById                       -[#000082,plain]-^  Command
RemoveFirst                      -[#000082,plain]-^  Command
Show                             -[#000082,plain]-^  Command
Sort                             -[#000082,plain]-^  Command
StandartConsole                  -[#008200,dashed]-^  Console
Studio                           -[#008200,dashed]-^  Validatable
Update                           -[#000082,plain]-^  AskingCommand
@enduml
